services:
  backend:
    build: ./backend
    container_name: node-backend
    restart: always
    expose:
      - 5000
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"  # 🟢 Changed from 80:80 to 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
